#!/bin/bash
## Run the livebench benchmark in parallel using the specified models
## For each model, this script will run gen_api_answer and then gen_ground_truth_judgment for the specified benchmark subset.
## Each model is run in a separate tmux session
## The question-source argument is optional; if not provided, the questions will be downloaded from huggingface
## Usage: run_livebench_parallel_models <venv-path> <question-source>
## Example: run_livebench_parallel_models ../.venv/bin/activate jsonl

venv=$1
question_source=$2

if [ -z "$venv" ]; then
    echo "Usage: run_livebench_parallel_models <venv-path> <optional-question-source>"
    exit 1
fi

echo "Running livebench benchmarks in parallel using $venv"

MODELS=(
    # OpenAI:
    # "o1-2024-12-17"
    # "o1-mini-2024-09-12"
    # "gpt-4o-2024-11-20"
    # "gpt-4o-mini-2024-07-18"
    # "chatgpt-4o-latest"

    # Google:
    # "gemini-2.0-flash-thinking-exp-1219"
    # "gemini-exp-1206"
    # "gemini-2.0-flash-exp"
    # "gemini-exp-1121"
    # "gemini-1.5-pro-002"
    # "gemini-1.5-flash-002"
    # "learnlm-1.5-pro-experimental"
    # "gemma-2-27b-it"
    # "gemini-1.5-flash-8b-exp-082"

    # DeepSeek:
    # "deepseek-v3"
    "deepseek-r1"

    # Anthropic:
    # "claude-3-5-sonnet-20241022"
    # "claude-3-opus-20240229"
    # "claude-3-5-haiku-20241022"

    # xAI:
    # "grok-2-1212"
    # "grok-beta"

    # Meta:
    "meta-llama-3.1-405b-instruct-turbo"
    # "meta-llama-3.1-70b-instruct-turbo"
    "llama-3.3-70b-instruct-turbo"

    # Alibaba:
    # "qwen2.5-72b-instruct-turbo"
    # "qwen2.5-7b-instruct-turbo"

    # Mistral:
    # "mistral-large-2411"
    # "mistral-small-2409"
    # "open-mixtral-8x22b"

    # Amazon:
    # "amazon.nova-pro-v1:0"
    # "amazon.nova-lite-v1:0"
    # "amazon.nova-micro-v1:0"

    # Cohere:
    # "command-r-08-2024"
    # "command-r-plus-08-2024"
)

# For each model
for model in "${MODELS[@]}"; do
    ./scripts/run_livebench_parallel $model $venv $question_source
done

echo "Benchmark tmux sessions:"
tmux ls