agent:
  type: default
  tools:
    env_variables:
      WINDOW: 200
      OVERLAP: 3
    execution_timeout: 300
    bundles:
      - path: tools/registry
      - path: tools/multilingual_setup
      - path: tools/defaults
      - path: tools/search
      - path: tools/edit_replace
      - path: tools/review_on_submit_m
    enable_bash_tool: true
    registry_variables:
      USE_FILEMAP: 'true'
      SUBMIT_REVIEW_MESSAGES:
        - |
          Thank you for your work on this issue. Please carefully follow the steps below to help review your changes.

          1. If you made any changes to your code after running the reproduction script, please run the reproduction script again.
            If the reproduction script is failing, please revisit your changes and make sure they are correct.
            If you have already removed your reproduction script, please ignore this step.
          2. Remove your reproduction script (if you haven't done so already).
          3. If you have modified any TEST files, please revert them to the state they had before you started fixing the issue.
            You can do this with `git checkout -- /path/to/test/file`. Use below <diff> to find the files you need to revert.
          4. Run the submit command again to confirm.

          Here is a list of all of your changes:

          <diff>
          {{diff}}
          </diff>
  history_processors:
    - type: last_n_observations
      n: 5
  model:
    per_instance_call_limit: 50
    per_instance_cost_limit: 0
    total_cost_limit: 0
    temperature: 0
    top_p: null